"""Add soft delete

Revision ID: 70bc12c0a4c9
Revises: 3df8027e5715
Create Date: 2026-04-13 12:59:14.403068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70bc12c0a4c9'
down_revision: Union[str, Sequence[str], None] = '3df8027e5715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_products_is_deleted'), 'products', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_is_deleted'), table_name='products')
    op.drop_column('products', 'is_deleted')
    # ### end Alembic commands ###
